# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^docs/"
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: no-commit-to-branch
            args: [--branch, master]
  -   repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
        - id: isort
          additional_dependencies:
            - toml
          types: [python]
  -   repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
        -   id: black
  -   repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          args: ["--max-line-length=120"]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.4.1
      hooks:
        - id: mypy
          additional_dependencies: ['types-pytz']
  -   repo: https://github.com/yunojuno/pre-commit-xenon
      rev: v0.1
      hooks:
        - id: xenon
          args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
